# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_name',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
