# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0003_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='std_url',
            field=models.CharField(default='hola', max_length=200),
            preserve_default=False,
        ),
    ]
