# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0004_video_std_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='time',
            field=models.DateTimeField(verbose_name='time of download'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([('video',)]),
        ),
    ]
